databases:
  - name: micronaut 
    databaseName: micronaut_cblb
    user: micronaut_cblb_user

services:
  - type: web
    name: dazzle
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false